### ISSUE TITLE
Add more information about Cache TTL

### ISSUE THREAD

**Issue by HazCod** [Moinax/TvDb#22]
First of all, thank you for your library!
Some more documentation about the ttl setting in your CacheClient would be appropriate.
Is this seconds, ms, ... ?

Thank you.

**Comment by Moinax** [comment]
Hi, thank you for your message.

A cache ttl is usually in seconds, so we didn't think it would be necessary to document it ;)

But you can make a pull request to update the documentation if you want.

Regards,

**Comment by HazCod** [comment]
Just a quick follow up that the caching is working great, thank you for your work on this. :+1:
