### ISSUE TITLE
Documentation about using this script in Symfony2

### ISSUE THREAD

**Issue by gittix09** [Moinax/TvDb#24]
Hello!!  
I would like to "import" this script in a Symfony2 project.   
How can I do that?  
What do we need to do in order to call

    $tvdb->getSerie(75710);

inside a Symfony2 controller?
  

For example look at the documentation of FosUserBundle:  
https://github.com/FriendsOfSymfony/FOSUserBundle/blob/1.3.x/Resources/doc/index.md

**Comment by Moinax** [comment]
Hi @gittix09 , what you show me as an example is a Symfony Bundle.

The Tvdb api is a simple component (library). So like any other component, you install it with composer, then you only need to create a Symfony service with the Tvdb client class.

See http://symfony.com/doc/current/book/service_container.html

Regards,

**Comment by gittix09** [comment]
Thank you very much... I will try what you suggested

**Comment by gittix09** [comment]
I got it working, BUT I have two questions.

Current situation:
I placed the project folder in the Acme/DemoBundle directory.
So the Client.php path is:  
src/Acme/DemoBundle/Moinax/TvDb/Client.php

Then, I declared a service like this:  

    my_tvdb:
        class: Acme\DemoBundle\Moinax\TvDb\Client
        arguments: ["http://thetvdb.com", my_api_key]

This works fine, but:
1) I would prefer to put the "Moinax" folder under the "vendor" folder... If I do that what path do I need to use in the my_tvdb.class service? How can I reference a resource that is under the vendor folder?
2) I had to prefix the namespace of ALL the php files in the Moinax folder with "Acme\Demo\". Is there a better way to avoid this?

**Comment by Moinax** [comment]
Hi @gittix09 

If you do a composer require moinax/tvdb, the component will be installed in the vendor folder as expected.

Then you simply have to use the full namespace of the class and the autoloader will do the rest for you.

    my_tvdb:
        class: Moinax\TvDb\Client
        arguments: ["http://thetvdb.com", my_api_key]

**Comment by gittix09** [comment]
Great!! I confirm it works. Thank you very much for the help
