### ISSUE TITLE
interface Cache not found

### ISSUE THREAD

**Issue by revalabdillah** [Moinax/TvDb#25]
I get an error when using cache mode

<b>Fatal error:</b> Interface 'Moinax\TvDb\Http\Cache\Cache' not found in <b>F:\xampp\htdocs\anjing\src\Moinax\TvDb\Http\Cache\FilesystemCache.php</b> on line <b>5</b>

**Comment by RobinHoutevelts** [comment]
I can't reproduce this.

I'm also using the FilesystemCache as explained in the Readme.
It works _very_ fine for me.

**Comment by Moinax** [comment]
That was my guess too, I'm closing this... 

Regards,
