### ISSUE TITLE
Spelling: serie vs series

### ISSUE THREAD

**Issue by zeebinz** [Moinax/TvDb#26]
Quibble, but the singular of "series" is "series", not "serie". This causes some confusion with the differently named methods like `getSeries()` vs `getSerie()`, `getSerieByRemoteId()`, when the endpoint is actually GetSeriesByRemoteID.php, for instance.

Otherwise nice library with handy caching functions, good work.

**Comment by Moinax** [comment]
Thank you, it's because I'm Belgian, and we said "Série" for singular and "Séries" for plural, so I made the mistake long time ago.

You are free to pull a request. Maybe we can change them to "getShow" and "getShows".

**Comment by zeebinz** [comment]
English is a stupid language sometimes ;) I can live with it as it is for now, thanks again for your work especially on the caching.

**Comment by Moinax** [comment]
Have a great time using it :)
