### ISSUE TITLE
Ordering episode results by season

### ISSUE THREAD

**Issue by bernsie** [Moinax/TvDb#29]
Currently I am fetching my results like so
```php
$episodes = $tvdb->getEpisodes($searchTerm);
```
and displaying them inside a view with blade
```php
<ul>
    @foreach($episodes as $episode)
        <li class="item">
            <p>
                {!! $episode->number !!}: {!! $episode->name !!}
           </p>
        </li>
    @endforeach
</ul>
```

my goal is to somehow create a season title and group the episodes, the closest ive come is adding  
```php
<h4>{!! $episode->season !!}</h4>
```
however this adds it above each episode does anyone have an approach to acomplish this?

Ex.
### Season 1
- ep 1
- ep 2
- ep 3

### Season 2
- ep 1
- ep 2
- ep 3

**Comment by Poverty11** [comment]
Simple solution would be to find episode 1 and add the season title before it.
(This will work if you are listing all episodes on the same page.

Example: http://tv.timh.info/examples/seasontitle.php

**Comment by bernsie** [comment]
@Poverty11 that is what i am going for is there a way i can get the un-rendered php?

**Comment by Poverty11** [comment]
I see you closed the thread, did you sort it?

**Comment by bernsie** [comment]
@Poverty11 yes i posted results above

**Comment by Poverty11** [comment]
Awesome, I'm currently trying to make some sort of ajax script to load the different seasons on the page, without actually updating the page.
Not 100% sure how to tho.

**Comment by bernsie** [comment]
I could see maybe something like angular helping in that scenario
