### ISSUE TITLE
Property rating as float instead of string

### ISSUE THREAD

**Issue by RobinHoutevelts** [Moinax/TvDb#30]
Hi,

I noticed you explicitly set the `rating` ( and sometimes `ratingCount` ) property as a string.
Is there any specific reason? I'd expect this to be a float and integer respectively.

In [Episode.php](https://github.com/Moinax/TvDb/blob/2e6b98f7566ab4befa3948fe468d261a827b919a/src/Moinax/TvDb/Episode.php#L118) you set `ratingCount` as an integer. But in [Serie.php](https://github.com/Moinax/TvDb/blob/2e6b98f7566ab4befa3948fe468d261a827b919a/src/Moinax/TvDb/Serie.php#L159) you don't.

Furthermore I'd expect all `rating` properties to be a float.
But I see that's not the case:
 - [Banner.php](https://github.com/Moinax/TvDb/blob/2e6b98f7566ab4befa3948fe468d261a827b919a/src/Moinax/TvDb/Banner.php#L89)
 - [Serie.php](https://github.com/Moinax/TvDb/blob/2e6b98f7566ab4befa3948fe468d261a827b919a/src/Moinax/TvDb/Serie.php#L158)
 - [Episode.php](https://github.com/Moinax/TvDb/blob/2e6b98f7566ab4befa3948fe468d261a827b919a/src/Moinax/TvDb/Episode.php#L118)

If there's a reason behind this could you let me know?

Regards,
Robin

**Comment by Moinax** [comment]
I think that's because the content coming from tvdb was not always sent as a float and that throws exceptions in my project.

**Comment by RobinHoutevelts** [comment]
Oh ok, in that case I'll wrap it in a try/catch.
I'll update my PR in a few hours.

Regards,
Robin
Op 20-dec.-2015 11:05 AM schreef "Jérôme Poskin" <notifications@github.com>:

**Comment by RobinHoutevelts** [comment]
After doing a few tests, it seems that casting strings to float **never** throws exceptions.
It just defaults to `0.00` which would be the expected behaviour in case of invalid formats.

`$value` | `(float) $value`
--------- | -------------
| `"1.01"` | `1.01`|
| `"1.0"` | `1.00`|
| `"1,01"` | `1.00`|
| `"1.01a"` | `1.01`|
| `"a1.01"` | `0.00`|
| `"1"` | `1.00`|
| `"0"` | `0.00`|
| `"lorem ipsum"` | `0.00`|
| `""` | `0.00`|

I've also not found a case where TheTVDB *doesn't* already format the string in float notation.

Are you sure this isn't just a case where you were over-concerned with handling invalid strings?

Regards,
Robin

**Comment by Moinax** [comment]
It was a long time ago, if the cast is working for you, it's working for me then...
