### ISSUE TITLE
Can't get Actors

### ISSUE THREAD

**Issue by anita-mcqs** [Moinax/TvDb#35]
For some reason when I try to get the actors details using: 
<code>$actors  = $tvdb->getActors($showId);   </code>

I get the following error: 
Fatal error: Class 'Moinax\TvDb\Actor' not found in C:\laragon\www\src\Moinax\TvDb\Client.php on line 226

This is the line it seems to have the problem with: 
<code>$actors[] = new Actor($actor);</code>

I didn't edit the Actor file or the getActors function in the Client class. I had no problem with the getBanners function. I checked the $actor variable and it's seems to have the necessary data (it's not null).

It seems that the Client class doesn't seem to recognise the Actor class. 

Can you help please?

Thanks!

**Comment by Moinax** [comment]
Maybe did you forget to include the file manually like I did for the others in the example https://github.com/Moinax/TvDb/blob/master/examples/index.php

This should not be necessary if you use an autoload script with PSR0 standard like the one generated by composer https://getcomposer.org/.

**Comment by anita-mcqs** [comment]
Yes, that's what it was! Can't believe I missed it! Thanks!!

**Comment by Moinax** [comment]
No problem, I'm glad I could help.

Regards,
