### ISSUE TITLE
getSeries() @internal?

### ISSUE THREAD

**Issue by effem** [Moinax/TvDb#38]
Hi, is there any reason that the getSeries() method is marked as internal? My IDE marks this as "do not use" but the api endpoint behind the getSeries() method is publicly available so should the method be.

Are there any reasons against the public usage of this method?

**Comment by Moinax** [comment]
No it's my IDE who did something wrong in the doc block. I modified the code and I will create a new release with this tiny change ;)

**Comment by effem** [comment]
:+1: Tanks :)
