### ISSUE TITLE
APi v2?

### ISSUE THREAD

**Issue by scriptzteam** [Moinax/TvDb#43]
APIv2

A new version of the API has been written which uses JSON instead of XML files. Documentation for this version can be found at https://api.thetvdb.com/swagger. It is highly recommended that any new development be done using the new API. This version of the API will continue to function until October 1st, 2017 at which time it will be discontinued.

https://api.thetvdb.com/swagger

**Comment by Moinax** [comment]
Hi @scriptzteam, I'm well aware of that, but I have no time to create a new version of the client and there is already well written API 2.0 client available on github like https://github.com/adrenth/thetvdb2

Regards,
